"""Add passwords table, drop password column from users, add auth_method column to users

Revision ID: d86e362c6b90
Revises: 
Create Date: 2025-01-02 13:12:51.393887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86e362c6b90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Create new passwords table
    op.create_table('passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 2. Insert existing user (id) and password data into new passwords table
    op.execute("""
        INSERT INTO passwords (user_id, password)
        SELECT id, password FROM users WHERE password IS NOT NULL;
    """)

    # 3. Add 'auth_method' column to users table and update column for existing users. drop 'password' column.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_method', sa.String(), nullable=False, server_default='password'))
        batch_op.drop_column('password')

    # Update existing rows to set auth_method = 'password'. this is an explicit update as "server_default = 'password'" covers this
    # op.execute("UPDATE users SET auth_method = 'password'")

    # 4. Remove server_default for auth_method column after migration
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('auth_method', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    """Reverse/rollback to negate the above under 'upgrade'"""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Alter 'users' table to add a 'password' column and remove 'auth_method' column
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=False, server_default=""))
        batch_op.drop_column('auth_method')

    # 2. Copy back password from passwords table, back to 'password' column in users table.
    op.execute("""
        UPDATE users
        SET password = (SELECT password FROM passwords WHERE passwords.user_id = users.id)
    """)

    # 3. Drop the 'passwords' table
    op.drop_table('passwords')
    # ### end Alembic commands ###
